
# Test environment configuration for automated testing
version: '3.8'

services:
  app-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://test_user:test_password@postgres-test:5432/test_db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=test-secret-key
    command: npm test
    depends_on:
      postgres-test:
        condition: service_healthy
    volumes:
      - .:/app:cached
      - /app/node_modules
    networks:
      - test-network

  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - test-network

volumes:
  postgres_test_data:

networks:
  test-network:
    driver: bridge
