services:
  app:
    build:
      context: .
      target: development
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://gigsecure_dev_user:gigsecure_dev_password@postgres:5432/gigsecure_dev
      - NODE_OPTIONS=--max-old-space-size=4096
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    restart: unless-stopped
    user: "node"
    working_dir: /app
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: gigsecure_dev
      POSTGRES_USER: gigsecure_dev_user
      POSTGRES_PASSWORD: gigsecure_dev_password
      TZ: UTC
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gigsecure_dev_user -d gigsecure_dev"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres_dev_data:
    driver: local