
# Development override for docker-compose
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  app:
    build:
      target: base
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app:cached
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  postgres:
    ports:
      - "5433:5432"  # Different port for dev to avoid conflicts
    environment:
      POSTGRES_DB: gigsecure_dev
      POSTGRES_USER: gigsecure_dev_user
      POSTGRES_PASSWORD: gigsecure_dev_password

# Development-specific volumes
volumes:
  postgres_dev_data:
    driver: local
